Vertical scrolling and backend integration in Feed Tile
PozytywneInicjatywy/dashboard-front pull request #13
Opened 2017-11-30 20:00 UTC by lukasz-ciskowski

Added fetching data from backend and added vertical scrolling

2017-11-30 20:06 UTC, JakubBizewski requested changes

2017-11-30 20:06 UTC, DarkMuffinJoe commented on src/tiles/FeedTile.vue
> +    var marquee = require('../marquee')
It's best to avoid mixing standards. We're using `import` from ES6 and I think you should stick with it.

2017-11-30 20:52 UTC, Albert221 requested changes

2017-11-30 20:52 UTC, Albert221 commented on src/marquee.js
> +function Init(containerId, content)
- Maybe let's name it `Marquee`?
- `export default function Marquee(...)`

2017-11-30 20:52 UTC, Albert221 commented on src/marquee.js
> +var actualHeight=0
Don't use `var`s, use `let` or `const`

2017-11-30 20:52 UTC, Albert221 commented on src/marquee.js
> +	var crossMarquee=document.getElementById(content)
Where is any code style? Spaces surrounding operators!

2017-11-30 20:52 UTC, Albert221 commented on src/marquee.js
> +	setInterval(function(){
Space before opening bracket

2017-11-30 20:52 UTC, Albert221 commented on src/marquee.js
> +		crossMarquee.style.top=parseInt(marqueeheight)+8+"px"
AFAIR we use single quotes for this. @DarkMuffinJoe can relate?

2017-11-30 20:52 UTC, Albert221 commented on src/marquee.js
> +		crossMarquee.style.top=parseInt(crossMarquee.style.top)-marqueeSpeed+"px"
You forgot indentation here and below

2017-11-30 20:52 UTC, Albert221 commented on src/marquee.js
> +export {Init}
If you'll make it `default export...` then this line is redundant.

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            marquee.Init('marquee','vmarquee');
Blank line before this line.

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +                for(var i=0;i<this.feeds.length;i++){
Code style...

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +                    this.feeds[i].publishedAt = new Date(1000*this.feeds[i].publishedAt);
Code style again

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            font-size:1.1em;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            position:relative;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            height:100%;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            position:absolute;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            text-align:right;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            font-style:italic;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            padding:0.5vw 1vw 0;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            font-size:16px;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            text-align:right;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            padding:0 1vw 2vw;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            font-style:italic;
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +                        "title": "",
Single quotes

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +                feeds:[{
Space after property name

2017-11-30 20:52 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            marquee.Init('marquee','vmarquee');
And IMO you should not pass this second parameter, but get child of first parameter

2017-11-30 21:47 UTC, Albert221 requested changes

2017-11-30 21:47 UTC, Albert221 commented on src/marquee.js
> +const marqueeSpeed=1
Code style. Spaces surrounding operator

2017-11-30 21:47 UTC, Albert221 commented on src/marquee.js
> +export function Marquee(containerId) {
`default`!

2017-11-30 21:47 UTC, Albert221 commented on src/marquee.js
> +	var marqueeheight = document.getElementById(containerId).offsetHeight
`var`

2017-11-30 21:47 UTC, Albert221 commented on src/marquee.js
>  		if (parseInt(crossMarquee.style.top)>(actualHeight * (-1) + 8))
Code style. Spaces surrounding operators! Redundant parenthesizes outside `-1`

2017-11-30 21:47 UTC, Albert221 commented on src/marquee.js
> +			crossMarquee.style.top = parseInt(crossMarquee.style.top) - marqueeSpeed + 'px'
IMO it would be better to use template string here instead of concatenation.

2017-11-30 21:47 UTC, Albert221 commented on src/marquee.js
> +	}, 1000/30)
Code style. Spaces surrounding operator.

2017-11-30 21:47 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +    import { Marquee } from './../marquee'
Quick note: If you'll make `Marquee` a `default` export, then you'd want to remove this braces.

2017-11-30 21:47 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            { Marquee('marquee') };
What are those brackets for? o.O

2017-11-30 21:47 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +                    this.feeds[i].publishedAt = new Date(1000 * this.feeds[i].publishedAt);
IMO you should use moment.js for dates because we use this in other parts of the frontend, but it's up to you!

2017-12-01 17:29 UTC, Albert221 requested changes
You almost made it. Two minor things to fix and it's done ;)

2017-12-01 17:29 UTC, Albert221 commented on src/marquee.js
> +	var crossMarquee = document.getElementById(containerId).firstElementChild
**You still use `var`!!!**

2017-12-01 17:29 UTC, Albert221 commented on src/tiles/FeedTile.vue
> +            <div class="feed--scroll" id="vmarquee">
This id is redundant

2017-12-01 18:28 UTC, Albert221 approved these changes

2017-12-01 18:29 UTC, merged